export const sslcSubjects = [
    "firstLanguagePaperI",
    "firstLanguagePaperII",
    "english",
    "hindi",
    "socialScience",
    "physics",
    "chemistry",
    "biology",
    "mathematics",
    "informationTechnology",
];

export const subjectOptions = [
    "English",
    "Hindi",
    "Mathematics",
    "Science",
    "Social Science",
    "Physics",
    "Chemistry",
    "Biology",
    "Computer Applications",
    "Computer Science",
    "Information Technology",
    "Environmental Science",
    "History",
    "Geography",
    "Civics",
    "Economics",
    "Commercial Studies",
    "Malayalam",
    "Tamil",
    "Kannada",
    "Telugu",
    "Bengali",
    "Urdu",
    "Sanskrit",
    "French",
    "German",
    "Arabic",
    "Other"
];


export const sslcGradeOptions = [
    "A+",
    "A",
    "B+",
    "B",
    "C+",
    "C",
    "D+",
    "D",
    "E",
    "F",
    // "A1",
    // "A2",
    // "B1",
    // "B2",
    // "C1",
    // "C2",
    // "D1",
    // "D2",
];

export const gradeOptions = [
    "A+",
    "A",
    "B+",
    "B",
    "C+",
    "C",
    "D+",
    "D",
    "E",
    "F",
    "A1",
    "A2",
    "B1",
    "B2",
    "C1",
    "C2",
    "D1",
    "D2",
];

// subjects.js (or any file you want)
// subjects.js
export const optns = [
    // Plus Two Science subjects
    "Physics",
    "Chemistry",
    "Mathematics",
    "Biology",
    "Malayalam",
    "Computer Science",
    "Electronics",
    "Information Technology",
    "Engineering Graphics",
    "Biotechnology",
    "Technical Vocational Subject",

    // Plus Two Commerce/Other common subjects
    "Business Studies",
    "Entrepreneurship",
    "Economics",
    "Accountancy",
    "Physical Education",
    "English",
    "Hindi",

    // ITI typical subjects (basic/common)
    "Fitter",
    "Electrician",
    "Mechanic",
    "Welder",
    "Plumber",
    "Carpenter",
    "Automobile",
    "Machinist",
    "Computer Operator and Programming Assistant (COPA)",
    "Draftsman Civil",
    "Draftsman Mechanical",
    "Tool and Die Maker",
    "Information Technology and Electronics System Maintenance",

    "Agriculture",
    "Other",
];

